export const data = [
  {
    id: 1,
    title: "waffle",
    desc: "Waffle wit berries",
    price: "$6.5",
    img: "/images/image-waffle-mobile.jpg",
  },
  {
    id: 2,
    title: "creme Brulee",
    desc: "Vanilla Bean Creme Brulee",
    price: "$7.0",
    img: "/images/image-creme-brulee-mobile.jpg",
  },
  {
    id: 3,
    title: "Macaron",
    desc: "Macaron Mix of Five",
    price: "$8.0",
    img: "/images/image-macaron-mobile.jpg",
  },
  {
    id: 4,
    title: "Tiramisu",
    desc: "Classic Tiramisu",
    price: "$5.5",
    img: "/images/image-tiramisu-mobile.jpg",
  },
  {
    id: 5,
    title: "Pie",
    desc: "Lemon Meringue Pie",
    price: "$5.5",
    img: "/images/image-meringue-mobile.jpg",
  },
  {
    id: 6,
    title: "Cake",
    desc: "Red Velvet Cake",
    price: "$4.5",
    img: "/images/image-cake-mobile.jpg",
  },
  {
    id: 7,
    title: "Brownie",
    desc: "Salted Caramel Brownie",
    price: "$5.5",
    img: "/images/image-brownie-mobile.jpg",
  },
  {
    id: 8,
    title: "Panna Cotta",
    desc: "Vanilla Panna Cotta",
    price: "$6.5",
    img: "/images/image-panna-cotta-mobile.jpg",
  },
  {
    id: 9,
    title: "Baklava",
    desc: "Pistachio Balava",
    price: "$6.5",
    img: "/images/image-baklava-mobile.jpg",
  },
];
